"""Dicionario das 53 empresas da carteira.

Estrutura de cada empresa:
  forte    - nomes inequivocos (se aparece, e a empresa; aceita direto)
  fraco    - nomes ambiguos (curtos/comuns; so valem com termo de contexto junto)
  contexto - termos de setor/produto/executivo que confirmam a empresa
  ticker   - preenchido em runtime a partir da planilha da carteira
"""

EMPRESAS = {
 "Suzano": {"forte":["suzano"],"fraco":[],
            "contexto":["pulp","paper","celulose","eucalyptus","cellulose","beto abreu"]},
 "Amazon": {"forte":["amazon.com","amazon web services","aws"],"fraco":["amazon"],
            "contexto":["e-commerce","bezos","jassy","prime","cloud","retailer","seattle","kuiper"]},
 "Cisco": {"forte":["cisco systems"],"fraco":["cisco"],
           "contexto":["networking","router","switch","cybersecurity","chuck robbins","data center"]},
 "DirecTV": {"forte":["directv"],"fraco":[],
             "contexto":["satellite tv","pay tv","streaming","televisao","tv paga"]},
 "BMW": {"forte":["bmw group","bmw ag"],"fraco":["bmw"],
         "contexto":["car","vehicle","ev","automaker","munich","sedan","luxury car","carmaker"]},
 "Ford": {"forte":["ford motor","ford's","ford said","ford reported"],"fraco":["ford"],
          "contexto":["vehicle","ev","automaker","detroit","f-150","mustang","pickup","carmaker","electric vehicle"]},
 "Las Vegas Sands": {"forte":["las vegas sands","sands china"],"fraco":[],
                     "contexto":["casino","macao","macau","resort","gaming","integrated resort"]},
 "Toyota": {"forte":["toyota motor"],"fraco":["toyota"],
            "contexto":["car","vehicle","hybrid","automaker","prius","carmaker","japan"]},
 "Bristol Myers Squibb": {"forte":["bristol myers squibb","bristol-myers","bristol myers"],"fraco":[],
                          "contexto":["drug","pharma","fda","oncology","cancer","opdivo","therapy"]},
 "Elevance Health": {"forte":["elevance"],"fraco":[],
                     "contexto":["health insurance","insurer","medicaid","medicare","anthem","health plan"]},
 "Humana": {"forte":["humana"],"fraco":[],
            "contexto":["health insurance","medicare","insurer","medicare advantage","health plan"]},
 "Eli Lilly": {"forte":["eli lilly"],"fraco":["lilly"],
               "contexto":["drug","pharma","fda","mounjaro","zepbound","obesity","glp-1","diabetes","weight loss"]},
 "BP": {"forte":["british petroleum","bp plc","bp p.l.c"],"fraco":["bp"],
        "contexto":["oil","gas","energy","barrel","crude","refinery","petroleum","drilling"]},
 "ConocoPhillips": {"forte":["conocophillips","conoco phillips"],"fraco":[],
                    "contexto":["oil","gas","energy","crude","barrel","drilling","exploration"]},
 "Cosan": {"forte":["cosan","raizen"],"fraco":[],
           "contexto":["raizen","fuel","ethanol","sugar","logistics","rumo","combustivel"]},
 "Marathon Petroleum": {"forte":["marathon petroleum"],"fraco":[],
                        "contexto":["oil","refining","refinery","crude","fuel","downstream","gasoline"]},
 "Pemex": {"forte":["pemex"],"fraco":[],
           "contexto":["oil","mexico","crude","state oil","petroleum","refinery"]},
 "Chevron": {"forte":["chevron"],"fraco":[],
             "contexto":["oil","gas","energy","crude","barrel","refinery","drilling","permian"]},
 "Bank of America": {"forte":["bank of america","bofa"],"fraco":[],
                     "contexto":["bank","lender","trading","moynihan","wall street","deposits","loans"]},
 "BNP Paribas": {"forte":["bnp paribas"],"fraco":["bnp"],
                 "contexto":["bank","lender","paris","french bank","trading","loans"]},
 "Berkshire Hathaway": {"forte":["berkshire hathaway"],"fraco":["berkshire","buffett"],
                        "contexto":["warren buffett","omaha","insurance","conglomerate","abel"]},
 "Santander Mexico": {"forte":["santander mexico"],"fraco":[],
                      "contexto":["bank","mexico","lender","banking","loans"]},
 "Citigroup": {"forte":["citigroup","citibank"],"fraco":["citi"],
               "contexto":["bank","lender","wall street","trading","jane fraser"]},
 "CIBC": {"forte":["cibc","canadian imperial bank"],"fraco":[],
          "contexto":["bank","canada","lender","toronto","banking"]},
 "Deutsche Bank": {"forte":["deutsche bank"],"fraco":[],
                   "contexto":["bank","germany","lender","frankfurt","trading","investment bank"]},
 "Goldman Sachs": {"forte":["goldman sachs"],"fraco":["goldman"],
                   "contexto":["bank","wall street","trading","solomon","investment bank"]},
 "HSBC": {"forte":["hsbc"],"fraco":[],
          "contexto":["bank","lender","asia","hong kong","london","trading"]},
 "JPMorgan": {"forte":["jpmorgan","jp morgan","j.p. morgan"],"fraco":[],
              "contexto":["bank","dimon","trading","wall street","lender","deposits","investment bank"]},
 "Morgan Stanley": {"forte":["morgan stanley"],"fraco":[],
                    "contexto":["bank","wall street","trading","wealth management","investment bank","pick"]},
 "Royal Bank of Canada": {"forte":["royal bank of canada"],"fraco":["rbc"],
                          "contexto":["bank","lender","toronto","canadian bank"]},
 "Charles Schwab": {"forte":["charles schwab"],"fraco":["schwab"],
                    "contexto":["brokerage","broker","trading","investor","wealth"]},
 "Synchrony Financial": {"forte":["synchrony financial","synchrony"],"fraco":[],
                         "contexto":["consumer credit","credit card","lender","financing","store card"]},
 "UBS": {"forte":["ubs group","ubs ag"],"fraco":["ubs"],
         "contexto":["bank","swiss","zurich","wealth management","lender"]},
 "Wells Fargo": {"forte":["wells fargo"],"fraco":[],
                 "contexto":["bank","lender","trading","wall street","deposits","loans","scharf"]},
 "Blackstone": {"forte":["blackstone"],"fraco":[],
                "contexto":["private equity","asset management","fund","real estate","schwarzman","buyout"]},
 "Santander Holdings USA": {"forte":["santander holdings usa"],"fraco":[],
                            "contexto":["bank","lender","banking","auto loans"]},
 "Caterpillar": {"forte":["caterpillar"],"fraco":[],
                 "contexto":["machinery","construction","equipment","mining","heavy equipment","dealer"]},
 "Apple": {"forte":["apple inc","apple's","apple said","iphone maker"],"fraco":["apple"],
           "contexto":["iphone","ipad","macbook","tim cook","cupertino","ios","app store"]},
 "Microsoft": {"forte":["microsoft"],"fraco":[],
               "contexto":["azure","windows","cloud","nadella","copilot","xbox","software"]},
 "Accenture": {"forte":["accenture"],"fraco":[],
               "contexto":["consulting","technology","services","outsourcing","it services"]},
 "TSMC": {"forte":["tsmc","taiwan semiconductor"],"fraco":[],
          "contexto":["semiconductor","chip","foundry","taiwan","wafer","fab","3nm"]},
 "Disney": {"forte":["walt disney","disney+"],"fraco":["disney"],
            "contexto":["streaming","theme park","espn","hulu","iger","studio","box office","pixar","marvel"]},
 "United Airlines": {"forte":["united airlines"],"fraco":[],
                     "contexto":["airline","aviation","flights","carrier","jet","boeing","travel"]},
 "AbbVie": {"forte":["abbvie"],"fraco":[],
            "contexto":["drug","pharma","fda","humira","skyrizi","rinvoq","immunology","oncology"]},
 "Johnson & Johnson": {"forte":["johnson & johnson","johnson and johnson","j&j"],"fraco":[],
                       "contexto":["drug","pharma","fda","medical device","vaccine","healthcare","therapy"]},
 "Merck": {"forte":["merck & co","merck and co","merck sharp"],"fraco":["merck"],
           "contexto":["keytruda","drug","pharma","fda","cancer","vaccine","therapy","oncology"]},
 "Nestle": {"forte":["nestle"],"fraco":[],
            "contexto":["food","beverages","consumer","coffee","nespresso","kitkat","switzerland"]},
 "Novartis": {"forte":["novartis"],"fraco":[],
              "contexto":["drug","pharma","fda","therapy","cancer","switzerland","basel"]},
 "Roche": {"forte":["roche holding","roche diagnostics"],"fraco":["roche"],
           "contexto":["drug","pharma","fda","basel","cancer","trial","therapy","diagnostic"]},
 "Sandoz": {"forte":["sandoz"],"fraco":[],
            "contexto":["generics","biosimilar","pharma","drug","generic drugs"]},
 "UnitedHealth": {"forte":["unitedhealth","unitedhealthcare"],"fraco":[],
                  "contexto":["health insurance","medicare","insurer","optum","health plan","medicaid"]},
 "Zurich Insurance": {"forte":["zurich insurance"],"fraco":[],
                      "contexto":["insurance","insurer","switzerland","premiums","underwriting","reinsurance"]},
 "ABB": {"forte":["abb ltd","abb group"],"fraco":["abb"],
         "contexto":["automation","robotics","industrial","electrification","zurich","motor"]},
}


def carregar_tickers(df_carteira):
    """Recebe um DataFrame com colunas NOME e TICKER e preenche o ticker de cada empresa."""
    mapa = {str(r.get("NOME","")).strip(): str(r.get("TICKER","")).strip()
            for _, r in df_carteira.iterrows()}
    for nome in EMPRESAS:
        EMPRESAS[nome]["ticker"] = mapa.get(nome, "?")
    return EMPRESAS
